### PR TITLE
Added option to show Cython compilation output and display more informative error.

### PR DESCRIPTION
**Pull request by moorepants**

### CODE REVIEW

**Comment by moorepants** [comment]
@tjstienstra Any thoughts on this? Not sure if you are interested in reviewing things here.

**Comment by tjstienstra** [comment]
Haven't tested it, but it looks like a really nice feature. In terms of review, I can look at it if you like. As you currently always capture the output you may consider providing that in the error message as well.

**Comment by moorepants** [comment]
> As you currently always capture the output you may consider providing that in the error message as well.

Good idea.

**Comment by moorepants** [comment]
I'll go with this.

**Pull request merged**
