### PR TITLE
make plot_trajectories work if no input trajectories are given

### PR DESCRIPTION
**Pull request by Peter230655**
plot_trajectories tries to put the title _Input Trajectories_ on a non existing axis if no input trajectories are present.
I check whether they are present.

### CODE REVIEW

**Comment by moorepants** [comment]
LGTM

**Comment by Peter230655** [comment]
Thanks!!
Since you merged this, let me push a version of plot_estimate_parameters which uses plot_trajectories.
I will push tomorrow morning.

**Comment by moorepants** [comment]
Are you suggesting to plot the solutions to the unknown constants? Why would you plot single values like that? I can't think of a way to plot them that would have any utility.

**Comment by Peter230655** [comment]
Maybe part habit, partly I wanted to see how well the solutions with the estimated parameters would fit the 'true'
solution. That fit was actually better than the accuracy of the estimation of the dampening coefficient.
Accuracy of the solutions is within 2%, dampening is of by 15% as I recall. No idea why.
But you are right, trajectories not needed. I will remove and push again.

**Comment by Peter230655** [comment]
> Are you suggesting to plot the solutions to the unknown constants? Why would you plot single values like that? I can't think of a way to plot them that would have any utility.

At least like this I found the small problem in plot_trajectories. :-)

**Comment by moorepants** [comment]
In general, there is no "true" solution for the unknown constant parameters unless you artificially create the data used for the parameter identification.

**Comment by Peter230655** [comment]
> In general, there is no "true" solution for the unknown constant parameters unless you artificially create the data used for the parameter identification.

I artificially created the measurement data as described above, how else should I get 'measurement data'?
Is the basic approach correct, that is did I understand you correctly?
The convergence is quite fast, actually.

**Comment by moorepants** [comment]
> how else should I get 'measurement data'?

You would have to take measurements of something in real life.

**Comment by Peter230655** [comment]
> > how else should I get 'measurement data'?
> 
> You would have to take measurements of something in real life.

I am a retired salesman, I do not have measurement instruments. :-)
To me it is interesting how well opty found trajectories from very noisy 'measurements', which are close to the 'true' trajectory - known in the case on hand.

**Comment by moorepants** [comment]
I know that, I'm not implying you do so, but the point I'm trying to make is that a parameter identification problem, in general, has no known solution, so it does not make sense to add a plot function to opty to compare it against a nonexistent true solution.

**Comment by Peter230655** [comment]
> I know that, I'm not implying you do so, but the point I'm trying to make is that a parameter identification problem, in general, has no known solution, so it does not make sense to add a plot function to opty to compare it against a nonexistent true solution.

Now I think, I got your point. I will change things a bit a push.

**Pull request merged**
