### PR TITLE
Plot pendulum swing up variable duration

### PR DESCRIPTION
**Pull request by Peter230655**
Gave better initial guess and reduced the frames in the animation from around 500 to around 100. On my PC now it runs 13 sec, before 43 sec.

### CODE REVIEW

**Comment by moorepants** [comment]
This seems to be a mixture of two PRs.

**Comment by Peter230655** [comment]
> This seems to be a mixture of two PRs.

I do not know what happened:
This morning I pushed a branch ball_rolling_on_spinning_disc.
Now I pushed another branch plot_pendulum_swing_up_variable duration.
In my fork these are two different branches. 
It also aksed me to make a PR this moring and now again
Do I have to wait until a PR is merged or cancelled before I make the next one?

**Comment by Peter230655** [comment]
I am at a loss what to do.

**Comment by Peter230655** [comment]
I will close this PR and start an new on. For whatever reason, there a four files change, no idea why

**Pull request closed without merging**
