### PR TITLE
fixed issue when no instance constraints are given

### PR DESCRIPTION
**Pull request by Peter230655**
I corrected the problem, when no instance constraints are given. Basically just added a number of check whether nistance constraints are given.

### CODE REVIEW

**Comment by Peter230655** [comment]
N oidea what has happened now :-(

**Comment by moorepants** [comment]
I believe I have already fixed it here: https://github.com/csu-hmc/opty/commit/df995bbb9c6706704c276a41033809cbf877102e

**Comment by Peter230655** [comment]
> I believe I have already fixed it here: [df995bb](https://github.com/csu-hmc/opty/commit/df995bbb9c6706704c276a41033809cbf877102e)

I must have gotten it mixed up, because your first fix did not seem to work for me.
Should I simply close this PR?

**Comment by moorepants** [comment]
If the tip of master works and solves this issue, then you can close this PR.

**Comment by Peter230655** [comment]
> If the tip of master works and solves this issue, then you can close this PR.

I got the error here when there are no instance constraints:
image
If there are no instance constraints, all of this should be skipped?

**Comment by moorepants** [comment]
Yes there is a conflict and you'll have to fix that if you want this merged, but I think I fully fixed the issue. Please check the tip of master.

**Comment by Peter230655** [comment]
> Yes there is a conflict and you'll have to fix that if you want this merged, but I think I fully fixed the issue. Please check the tip of master.
Let me try.

**Comment by Peter230655** [comment]
Works perfect! Sorry about the unnecessary trouble!

**Pull request closed without merging**
