### PR TITLE
Correcting time step width of trajectory plots to equal node_time_int…

### PR DESCRIPTION
**Pull request by chris-konrad**
Fixing #282

### CODE REVIEW

**Comment by chris-konrad** [comment]
I don't think this can happen. The results of arrange and linspace with (num_collocation_nodes-1) are equivalent:

```
In[30]: np.arange(0, num_collocation_nodes * node_time_interval, node_time_interval)
Out[30]: array([0., 1., 2., 3., 4.])

In[31]: np.linspace(0, (num_collocation_nodes-1) * node_time_interval, num=num_collocation_nodes)
Out[31]: array([0., 1., 2., 3., 4.])
```

**Comment by Peter230655** [comment]
> I don't think this can happen. The results of arrange and linspace with (num_collocation_nodes-1) are equivalent:
> 
> ```
> In[30]: np.arange(0, num_collocation_nodes * node_time_interval, node_time_interval)
> Out[30]: array([0., 1., 2., 3., 4.])
> 
> In[31]: np.linspace(0, (num_collocation_nodes-1) * node_time_interval, num=num_collocation_nodes)
> Out[31]: array([0., 1., 2., 3., 4.])
> ```
> 
> It will not really matter which correction we choose. But the current behaviour is definitely not correct :)

...but if an existing simulation uses tf = interval * (num_nodes - 1), then your change will matter?

**Comment by chris-konrad** [comment]
I am not sure I understand you correctly. Where would a current simulation use `tf = interval * (num_nodes - 1)`?

**Comment by Peter230655** [comment]
Virtually all the simulations I know or wrote define the starting time t0, mostly t0 = 0 and the final time tf.
Then interval = (tf - t0) / (num_nodes - 1) [you may look at the simulations in examples-gallery]
I guess the advantage is, that you can play around with num_nodes for convergence without messing up the 'physics' of the problem.

As regards compatibility, I do not know for sure.

**Comment by Peter230655** [comment]
I have no preference, it is up to Jason to decide about this.

**Comment by chris-konrad** [comment]
Actually, @Peter230655, turns out there is a good reason to prefer linspace over arange. The latter is [less numerically stable](https://numpy.org/doc/stable/reference/generated/numpy.arange.html) when using non-integer steps. This actually caused two of the examples to fail after all.

So, we should keep using linspace and add the correction by -1 instead. 
```
        time = np.linspace(0,
                           (self.collocator.num_collocation_nodes-1) *
                           node_time_interval,
                           num=self.collocator.num_collocation_nodes)
```

**Comment by chris-konrad** [comment]
But yes indeed. The "error" is purely cosmetic and won't really be visible for large sample numbers.

**Comment by Peter230655** [comment]
> Actually, @Peter230655, turns out there is a good reason to prefer linspace over arange. The latter is [less numerically stable](https://numpy.org/doc/stable/reference/generated/numpy.arange.html) when using non-integer steps. This actually caused two of the examples to fail after all.
> 
> So, we should keep using linspace and add the correction by -1 instead.
> 
> ```
>         time = np.linspace(0,
>                            (self.collocator.num_collocation_nodes-1) *
>                            node_time_interval,
>                            num=self.collocator.num_collocation_nodes)
> ```

I had no idea about the instabilitiy of arange. I am not the biggest Python expert, so I always use linspace.
Looks to me your suggestion makes sense, based on the definition of tf = interval * (num_nodes - 1) as it is done in all examples I know.

**Comment by moorepants** [comment]
LGTM!

Thanks for your first contribution :)

**Pull request merged**
