### PR TITLE
Try Python 3.13 in CI.

### PR DESCRIPTION
**Pull request by moorepants**

### CODE REVIEW

**Comment by moorepants** [comment]
Can't test with Python 3.13 in our CI setup yet:

```
  Warning: 
  LibMambaUnsatisfiableError: Encountered problems while solving:
    - nothing provides _python_rc needed by python-3.13.0rc1-h3b4618f_0_cp313t
  
  Could not solve for environment specs
  The following package could not be installed
  └─ python 3.13**  is not installable because it requires
     └─ _python_rc, which does not exist (perhaps a missing channel).
  
  
  
  LibMambaUnsatisfiableError: Encountered problems while solving:
    - nothing provides _python_rc needed by python-3.13.0rc1-h3b4618f_0_cp313t
  
  Could not solve for environment specs
  The following package could not be installed
  └─ python 3.13**  is not installable because it requires
     └─ _python_rc, which does not exist (perhaps a missing channel).
```

**Comment by moorepants** [comment]
CI means "continuous integration".

**Comment by Peter230655** [comment]
> CI means "continuous integration".

The set up that does the testing for PRs for opty?

**Comment by moorepants** [comment]
Yes.

**Pull request closed without merging**
